AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Bookmark Vault API (health + bookmarks)

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 256
    Environment:
      Variables:
        MONGODB_SECRET_ID: dev/mongodb/uri
        DB_NAME: bookmark_vault
        COLLECTION: bookmarks

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowHeaders: ['content-type','x-user-id']
        AllowMethods: ['GET','POST','OPTIONS']

  ApiFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.handler
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:dev/mongodb/uri-*
      Events:
        Health:
          Type: HttpApi
          Properties: { ApiId: !Ref HttpApi, Path: /health,     Method: GET }
        GetBookmarks:
          Type: HttpApi
          Properties: { ApiId: !Ref HttpApi, Path: /bookmarks,  Method: GET }
        CreateBookmark:
          Type: HttpApi
          Properties: { ApiId: !Ref HttpApi, Path: /bookmarks,  Method: POST }
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints: [src/handler.ts]
        Minify: true
        Sourcemap: true
        Target: "es2020"
        Platform: "node"
        External: []

Outputs:
  ApiBaseUrl:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
